### ISSUE TITLE
UserWarning in `qax`

### ISSUE THREAD

**Issue by egg5154** [davisyoshida/lorax#10]
Hello, I am testing lorax on my flax model in jax 0.4.26, and I got warning like this:
```
/home/zyh/anaconda3/envs/jax_v0.4.26/lib/python3.10/site-packages/qax/implicit/implicit_array.py:306: UserWarning: Primitive concatenate was not handled by class LoraWeight, so implicit args will be materialized.
  warnings.warn(f'Primitive {primitive.name} was not handled by class {implicit_cls.__name__}, so implicit args will be materialized.')
```
Will this behavior cause numerical errors in calculation? Thanks!

**Comment by davisyoshida** [comment]
Yeah that's just saying that it had to actually compute a dense matrix during the forward or backward pass. It will be numerically correct still.

**Comment by egg5154** [comment]
Thanks!
