### ISSUE TITLE
Using lorax with class-based models

### ISSUE THREAD

**Issue by Sids2k** [davisyoshida/lorax#11]
Great work with lorax and qax!
I am trying to add LoRA to a pretrained model of [Octo](https://github.com/octo-models/octo/tree/main). 
The main model [OctoModel](https://github.com/octo-models/octo/blob/main/octo/model/octo_model.py#L26) is a class instead of a function. When I use `lora_model = lorax.lora(model)` on `model = OctoModel.load_pretrained("hf://rail-berkeley/octo-base")`, the output is a function instead of a class. All attributes of `model` are there in `lora_model` but all functions of `model` are lost (functions associated with `@struct.dataclass` and with `class OctoModel`). Is there any way to use lorax and ensure that `lora_model` is a class with the same functions and attributes as `model`? I hit a key error while fine-tuning at the [train_step](https://github.com/octo-models/octo/blob/main/scripts/finetune.py#L290) which tells me that the `model` used should not be a function.
Thanks a lot!

P.S. I've used your [example](https://github.com/davisyoshida/lorax/blob/1ebd0efa6c467974357bb9f73fe4a4967b487622/examples/huggingface_gpt2.py) to edit the [fine-tuning script](https://github.com/octo-models/octo/blob/main/scripts/finetune.py) but `model = FlaxGPT2LMHeadModel.from_pretrained('gpt2')` outputs a function not a class.

**Comment by davisyoshida** [comment]
I'm not familiar with octo's code, but because all jax models have to be pure functions at the end of the day, you just need to figure out how to write something like:

```python
def model_fn(params, arg1, arg2, ...):
    # call the model here, using a class etc
   return result
```

Then you can do `lora_fn = lorax.lora(model_fn)`, and it should work. Can you show me the code you have now?
