### ISSUE TITLE
How to use lorax in python3.8

### ISSUE THREAD

**Issue by tututu05** [davisyoshida/lorax#3]
good works! 
I hope use lorax in python3.8, but qax-0.2.0 require python3.10. How to use lorax in python3.8?
Please help me!

**Comment by davisyoshida** [comment]
You can try downgrading to the older version of lorax. Unfortunately the API is a bit clunkier, but it should still work on earlier python versions.

**Comment by tututu05** [comment]
Thanks！It‘s helpful
