### ISSUE TITLE
LoRA Hypernetworks for 3 dimensional kernels

### ISSUE THREAD

**Issue by PuR3Luck** [davisyoshida/lorax#7]
I am currently playing around with training the Transformer. I am also now wondering how I could apply this to convolutions as the kernel for the convolution has 3 dimensions?

_Originally posted by @PuR3Luck in https://github.com/davisyoshida/lorax/issues/6#issuecomment-1873266895_

**Comment by davisyoshida** [comment]
This should just be the same as the other setting, but you use the right shape for the conv kernel instead. Does that break?
