### ISSUE TITLE
How to save the parameters non-destructively?

### ISSUE THREAD

**Issue by giganttheo** [davisyoshida/lorax#8]
Hi, thank you for this very useful library.
How to save the LoRA parameters?
I need to implement training checkpointing, so I don't want to merge the parameters in a way that is not possible to unmerge. When using a msgpack on the LoRA weights, I get an error `TypeError: can not serialize 'LoraWeight' object`.
I guess it would be possible to export the dictionnary as a regular PyTree of JAX Array and then import the weights again as a LoRA weight class. However, I am not sure how to write this.

**Comment by davisyoshida** [comment]
The easiest thing to use is just pickle, the reason it won't work with FLAX's msgpack utilities out of the box is that you have to manually handle non-default types (see [here](https://github.com/google/flax/blob/7cbc3c13ecd8a1713732113dec7939d0b75342c6/flax/serialization.py#L280)).

If you specifically need to use msgpack, you can replace the LoraWeight instances with tuples by doing something like this:

```python
TAG = '_LoraWeight'

def _lora_to_tuple(lora_weight):
    return TAG, x.w, x.a, x.b, x.alpha

def _value_is_lora_tuple(x):
    return isinstance(x, tuple) and x[0] == TAG

def _lora_tuple_to_original(tup):
    _, w, a, b, alpha = tup
    return LoraWeight(w=w, a=a, b=b, alpha=alpha)

def pytree_loras_to_tuple(pytree):
    return jax.tree_map(
        lambda x: _lora_to_tuple(x) if isinstance(x, LoraWeight) else x,
        pytree,
        is_leaf=lambda x: isinstance(x, LoraWeight)
    )

def pytree_loras_to_tuple(pytree):
    return jax.tree_map(
        lambda x: _lora_to_tuple(x) if isinstance(x, LoraWeight) else x,
        pytree,
        is_leaf=lambda x: isinstance(x, LoraWeight)
    )

def pytree_tuples_to_loras(pytree):
    return jax.tree_map(
        lambda x: _lora_tuple_to_original(x) if _value_is_lora_tuple(x) else x,
        is_leaf=_value_is_lora_tuple
    )
```

Another option would be to entirely flatten the pytree and serialize the resulting list, then unflatten it after deserialization.

**Comment by giganttheo** [comment]
ok, thank you for the ideas, pickle is indeed quite easier to use than msgpack here
